# Jekyll Configuration for Kristoffer Ekstrand Portfolio
title: 'Kristoffer Ekstrand'
email: 'toffe@kristofferekstrand.se'
description: 'Digital Project Manager & Frontend Developer in Stockholm. 20+ years in digital products. Shopify, e-commerce, UX design, visual design & sound.'
baseurl: ''
url: 'https://kristofferkarlaxelekstrand.github.io'

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

# Performance optimization
incremental: true
profile: false

# HTML compression settings
compress_html:
    clippings: all
    comments: all
    endings: all
    startings: [html, head, body]
    blanklines: false
    profile: false

# SEO and metadata
author:
    name: 'Kristoffer Karl Axel Ekstrand'
    twitter: ''

# Site settings
timezone: Europe/Stockholm
locale: en_US
lang: en

# Collections Configuration
collections:
    workplaces:
        output: true
        permalink: /:collection/:name/
        sort_by: start_date
    projects:
        output: true
        permalink: /:collection/:name/
    lab_sites:
        output: true
        permalink: /:collection/:name/
    client_sites:
        output: true
        permalink: /:collection/:name/

# Default front matter
defaults:
    - scope:
          path: ''
      values:
          image: /icon-512.png
          sitemap:
              priority: 0.7
              changefreq: monthly
    - scope:
          path: ''
          type: 'workplaces'
      values:
          layout: 'workplace'
          sitemap:
              priority: 0.8
              changefreq: yearly
    - scope:
          path: ''
          type: 'projects'
      values:
          layout: 'project'
          sitemap:
              priority: 0.8
              changefreq: yearly
    - scope:
          path: ''
          type: 'lab_sites'
      values:
          layout: 'site'
          sitemap:
              priority: 0.6
              changefreq: monthly
    - scope:
          path: ''
          type: 'client_sites'
      values:
          layout: 'site'
          sitemap:
              priority: 0.7
              changefreq: yearly

# Sass configuration
sass:
    sass_dir: _sass
    style: compressed
    sourcemap: false

# Feed optimization
feed:
    collections:
        - workplaces
        - projects
    excerpt_only: true

# Exclude from processing
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - legacy-build/
    - docs-implementation/
    - reference/
    - package.json
    - package-lock.json
    - README.md
    - REPOSITORY-STRUCTURE.md
    - .vscode/
    - .github/

# Include files that start with underscores
include:
    - _pages
