name: pages-build-deployment

# Override GitHub's default pages-build-deployment workflow
# This prevents the automatic workflow from running
on:
    workflow_dispatch:
        # Only allow manual triggering, never automatic

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Override default Pages workflow
              run: |
                  echo "Default GitHub Pages workflow overridden."
                  echo "Using custom 'Build and Deploy' workflow instead."
                  echo "This workflow will never run automatically."
